Develop/hw 7
harisov-mobile/kts-2023-strava-app pull request #6
Opened 2023-06-04 18:49 UTC by harisov-mobile

Домашнее задание № 7.
Сделаны пункты:
- Экран Онбоардинг - только при первом запуске приложения (используется SharedPrefs);
- Токен сохраняется в SharedPrefs, экран авторизации - если токен есть - не открывается;
- Room - если данные с сервера не удалось получить - получаем из Room и отображаем "плашку".
- pull to refresh на экран со списком сущностей;
- если токен "протух" - обновляется токен;
- логаут из приложения - перенаправление на экран логина.

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/training/list/TrainingListScreen.kt
> +                        }
remember, в списках можно его использовать если есть id

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/training/detail/TrainingDetailViewModel.kt
> +                    )
Сделай лучше через StringVs подход, тогда не нужно будет application тащить во view model и другие места. Как использовать во viewmodel -> `R.string.title.toStringVs()`. Как использовать в compose  -> context.parseStringVs(title) или написать еще метод для compose в котором с помощью LocalContext.current контекст достается, чтобы было проще использовать


```kotlin
import android.content.Context
import android.view.View
import androidx.annotation.PluralsRes
import androidx.annotation.StringRes
import androidx.fragment.app.Fragment

sealed class StringVs {
    data class StringFormatResource(
        @StringRes val id: Int,
        val formatArgs: List<Any>
    ) : StringVs()

    data class StringPlural(
        @PluralsRes val id: Int,
        val quantity: Int,
        val formatArgs: List<Any>
    ) : StringVs()

    data class StringResource(
        @StringRes val id: Int
    ) : StringVs()

    data class StringValue(val string: String) : StringVs()
}

// annotations for receiver lints not working for now
fun @receiver:StringRes Int.toStringVs(): StringVs {
    return StringVs.StringResource(this)
}

fun @receiver:StringRes Int.toStringVs(vararg formatArgs: Any): StringVs {
    return StringVs.StringFormatResource(this, formatArgs.toList())
}

fun @receiver:StringRes Int.toStringVs(formatArgs: List<Any?>): StringVs {
    val args = formatArgs.mapNullToDefault("")
    return StringVs.StringFormatResource(this, args)
}

fun @receiver:PluralsRes Int.toPluralStringVs(quantity: Int, vararg formatArgs: Any): StringVs {
    return StringVs.StringPlural(this, quantity, formatArgs.toList())
}

fun @receiver:PluralsRes Int.toPluralStringVs(quantity: Int, formatArgs: List<Any?>): StringVs {
    val args = formatArgs.mapNullToDefault("")
    return StringVs.StringPlural(this, quantity, args)
}

fun String.toStringVs(): StringVs {
    return StringVs.StringValue(this)
}

fun List<Any?>.mapNullToDefault(defaultVal: Any) =
    map { it ?: defaultVal }

fun View.parseStringVsOrNull(stringVs: StringVs?): String? =
    context.parseStringVsOrNull(stringVs)

fun View.parseStringVs(stringVs: StringVs): String =
    context.parseStringVs(stringVs)

fun View.parseStringVsInPlace(@StringRes stringRes: Int): String =
    parseStringVs(stringRes.toStringVs())

fun Fragment.parseStringVsOrNull(stringVs: StringVs?): String? =
    requireContext().parseStringVsOrNull(stringVs)

fun Fragment.parseStringVs(stringVs: StringVs): String =
    requireContext().parseStringVs(stringVs)

fun Fragment.parseStringVsInPlace(@StringRes stringRes: Int): String =
    parseStringVs(stringRes.toStringVs())

fun Context.parseStringVsOrNull(stringVs: StringVs?): String? =
    stringVs?.let { parseStringVs(it) }

fun Context.parseStringVsInPlace(@StringRes stringRes: Int): String =
    parseStringVs(stringRes.toStringVs())

fun Context.parseStringVsInPlace(vararg formatArgs: Any, @StringRes stringRes: Int): String =
    parseStringVs(stringRes.toStringVs(*formatArgs))

fun Context.parseStringVsInPlace(@StringRes stringRes: Int, formatArgs: List<Any?>): String =
    parseStringVs(stringRes.toStringVs(formatArgs))

fun Context.parseStringVsInPlace(
    vararg formatArgs: Any,
    @PluralsRes stringRes: Int,
    quantity: Int,
): String =
    parseStringVs(stringRes.toPluralStringVs(quantity, *formatArgs))

fun Context.parseStringVsInPlace(
    @PluralsRes stringRes: Int,
    quantity: Int,
    formatArgs: List<Any?>
): String =
    parseStringVs(stringRes.toPluralStringVs(quantity, formatArgs))

fun Context.parseStringVs(stringVs: StringVs): String {
    return when (stringVs) {
        is StringVs.StringFormatResource -> getString(
            stringVs.id,
            *stringVs.formatArgs.toTypedArray()
        )
        is StringVs.StringPlural -> resources.getQuantityString(
            stringVs.id,
            stringVs.quantity,
            *stringVs.formatArgs.toTypedArray()
        )
        is StringVs.StringResource -> getString(
            stringVs.id
        )
        is StringVs.StringValue -> stringVs.string
    }
}
```

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/start/StartViewModel.kt
> +            if (token.accessToken.isNullOrEmpty()) {
Лучше сделать метод типа isAuthorized который будет это проверять, так читаемость будет лучше и переиспользовать проще, т.e. надо AuthUseCase сделать или если понадобится где то, просто вызовишь и заиспользуешь метод

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/start/StartViewModel.kt
> +        val onboardingParams = getOnboardingParamsUseCase.getOnboardingParams()
название неправильное, должно быть isFirstLaunch и все, к онбордингу значения никакого не имеет

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/auth/network/TokenStorage.kt
> +    fun readTokenFromPrefs() {
не используешь

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/auth/network/TokenStorage.kt
> +        TokenSharedPreferencesStorage.saveTokenData(
Зачем тебе две одинаковые сущности, избавься от одной. TokenStorage пвторяет то же что и TokenSharedPreferencesStorage. +  можно зыбыть обновить проперти в TokenStorage, бери всегда из хранилища и сохраняй туда актуальные данные при рефреше

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/main/MainScreenViewModel.kt
> +            when (val logoutDataResponse = logoutUseCase.logout()) {
не используешь проперти

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/main/MainScreenViewModel.kt
> +                    screenEventChannel.trySend(MainScreenEvent.NavigateToLogout(args = args))
уверен что нужно выходить на экран логина? Что делает logout api?

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/main/MainScreenViewModel.kt
> +    private val logoutRepository = LogoutRepositoryImpl()
Пока нормально, но когда DI появится нужно будет убирать

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/start/StartViewModel.kt
> +        val onboardingParams = getOnboardingParamsUseCase.getOnboardingParams()
главный поток еще блокируешь, данные нужно из io потока читать, ниже тоже

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/onboarding/OnboardingSharedPreferencesStorage.kt
> +object OnboardingSharedPreferencesStorage {
тоже замечание, да ты показываешь онбординг если первый запус, но хранилище к онбордингу не отностися, оно просто хранит первый запуск

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/start/StartViewModel.kt
> +            if (token.accessToken.isNullOrEmpty()) {
и getToken главный поток блокирует

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/auth/network/AuthRepository.kt
> +        TokenStorage.idToken = null
Вот о чем я говорил, ты зануляешь просто переменные, а нужно зачищать хранилище, я бы избавился от TokenStorage

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/logout/repository/LogoutRepositoryImpl.kt
> +        TokenStorage.saveTokenToPrefs()
очень не очевидно, я бы сделал просто метод clear и все было бы ясно, а тут зануляются переменные, а потом вызывается сохранение и чтобы понять приходится разбираться зачем и проваливаться дальше

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/profile/cache/datasource/ProfileLocalDataSource.kt
> +    suspend fun getProfile(): ProfileDbModel?
Модели для бд называют Local* - LocalProfile

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/common/database/AppDao.kt
> +    @Query("SELECT * FROM ${ProfileContract.TABLE_NAME} LIMIT 1")
LIMIT 1 явно лишний, нужно позаботиться чтобы одна запись была

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/common/database/AppDao.kt
> +    @Query("SELECT * FROM ${TrainingContract.TABLE_NAME} WHERE ${TrainingContract.Columns.ID} = :id LIMIT 1")
LIMIT лишний - у тебя id primary key (уникальный), поэтому он либо одно найдет либо ничего

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/training/detail/TrainingDetailScreen.kt
> +    val showDropdownMenu = remember { mutableStateOf(false) }
использовать делегат удобнее, не надо .value постоянно вызывать

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/domain/common/util/DateConverter.kt
> +        return SimpleDateFormat(DATE_TIME_FORMAT).parse(dateString)
SimpleDateFormat(*) надо вынести чтобы постоянно не создавать instance

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/util/DurationPiker.kt
> +                                Text(text = "ч.", modifier = Modifier.weight(0.3f))
ресурсы

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/util/DurationPiker.kt
> +                                    text = "OK"
ресурсы

2023-06-08 23:04 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/training/list/TrainingListScreen.kt
> +    }
это должно вызваться один раз? Выглядит как будто нужно вызывать в LaunchedEffect

2023-06-09 11:09 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/training/list/TrainingListScreen.kt
> +                        }
Сделал remember для лямбда-функции нажатия на элемент списка

2023-06-10 08:05 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/training/detail/TrainingDetailViewModel.kt
> +                    )
Да, сделал через StringVs - прям супер метод!

2023-06-10 13:25 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/start/StartViewModel.kt
> +            if (token.accessToken.isNullOrEmpty()) {
Переделал на AuthUseCase, убрал в корутину и flow.

2023-06-10 13:46 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/start/StartViewModel.kt
> +        val onboardingParams = getOnboardingParamsUseCase.getOnboardingParams()
Переименовал на GetFirstLaunchUseCase, убрал в корутину вызов.

2023-06-10 13:48 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/data/auth/network/TokenStorage.kt
> +    fun readTokenFromPrefs() {
Вообще удалил класс TokenStorage, буду использовать TokenSharedPreferencesStorage - оттуда читать токен в AuthorizationInterceptor сразу.

2023-06-10 13:49 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/data/auth/network/TokenStorage.kt
> +        TokenSharedPreferencesStorage.saveTokenData(
Думал, что чтение токена из объекта, находящегося в памяти - будет быстрее. Но, видимо, это усложняет код и делает его неустойчивым, поэтому удалил класс TokenStorage, буду использовать TokenSharedPreferencesStorage - оттуда читать токен в AuthorizationInterceptor сразу.

2023-06-10 14:01 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/main/MainScreenViewModel.kt
> +                    screenEventChannel.trySend(MainScreenEvent.NavigateToLogout(args = args))
Не заработало для сайта strava нормальный логаут OAuth, как в лекции Максима Мялкина - нет такой страницы отвечает сервер, и логаут, который в документации Strava - тоже ничего не дает, но я его все же вызываю на всякий случай: https://developers.strava.com/docs/authentication/  вызываю "The endpoint is POST https://www.strava.com/oauth/deauthorize"
Приходится в любом случае уходить на Фрагмент AuthFragment самому.

2023-06-10 14:02 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/main/MainScreenViewModel.kt
> +            when (val logoutDataResponse = logoutUseCase.logout()) {
Не заработало для сайта strava нормальный логаут OAuth, как в лекции Максима Мялкина - нет такой страницы отвечает сервер, и логаут, который в документации Strava - тоже ничего не дает, но я его все же вызываю на всякий случай: https://developers.strava.com/docs/authentication/  вызываю "The endpoint is POST https://www.strava.com/oauth/deauthorize"
Приходится в любом случае уходить на Фрагмент AuthFragment самому.

2023-06-10 14:03 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/data/onboarding/OnboardingSharedPreferencesStorage.kt
> +object OnboardingSharedPreferencesStorage {
Переименовал хранилище на FirstLaunchSharedPreferencesStorage.

2023-06-10 14:04 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/data/auth/network/AuthRepository.kt
> +        TokenStorage.idToken = null
Да, от TokenStorage избавился.

2023-06-10 14:05 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/data/logout/repository/LogoutRepositoryImpl.kt
> +        TokenStorage.saveTokenToPrefs()
Сделал метод clearToken()

2023-06-10 16:24 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/data/profile/cache/datasource/ProfileLocalDataSource.kt
> +    suspend fun getProfile(): ProfileDbModel?
Переименовал модельки БД в Local*

2023-06-10 16:25 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/data/common/database/AppDao.kt
> +    @Query("SELECT * FROM ${ProfileContract.TABLE_NAME} LIMIT 1")
Да, убрал LIMIT поставил перед добавлением - удаление, чтобы таблица перед добавлением была пустая.

2023-06-10 16:26 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/data/common/database/AppDao.kt
> +    @Query("SELECT * FROM ${TrainingContract.TABLE_NAME} WHERE ${TrainingContract.Columns.ID} = :id LIMIT 1")
Убрал LIMIT (Лимит на всякий случай делал, но похоже - не надо)

2023-06-10 17:04 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/training/detail/TrainingDetailScreen.kt
> +    val showDropdownMenu = remember { mutableStateOf(false) }
везде где используется collectAsStateWithLifecycle  применил "by"

2023-06-11 04:19 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/domain/common/util/DateConverter.kt
> +        return SimpleDateFormat(DATE_TIME_FORMAT).parse(dateString)
Вынес SimpleDateFormat в отдельные переменные.

2023-06-11 05:07 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/training/list/TrainingListScreen.kt
> +    }
Данный код будет срабатывать один раз, при изменении конфигурации второй раз не будет срабатывать за счет оператора remove:   shouldRefresh = currentBackStackEntry?.savedStateHandle?.remove<Boolean?>(refreshKey)
Возможно, что тянуть этот refresh в LaunchedEffect не надо.

2023-06-11 07:06 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/util/DurationPiker.kt
> +                                    text = "OK"
Исправил

2023-06-11 07:06 UTC, harisov-mobile commented on app/src/main/java/ru/internetcloud/strava/presentation/util/DurationPiker.kt
> +                                Text(text = "ч.", modifier = Modifier.weight(0.3f))
Исправил

2023-06-16 20:42 UTC, TimurChikishev requested changes

2023-06-16 20:42 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/firstlaunch/FirstLaunchSharedPreferencesStorage.kt
> +    fun isFirstLaunch(): Boolean = firstLaunchSharedPrefs.getBoolean(KEY_FIRST_LAUNCH, true)
Чтение и запись должны быть в io потоке и методы должны быть suspend. Если бы использовал DataStore то  проблемы бы не было, т.к. он под капотом сам поток переключает, но SharedPreferences так не умеет. Сделай везде где читаешь и записывпешь методы suspend и переключай поток с помощью withContext(Dispatcher.IO) {}

2023-06-16 20:42 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/training/detail/TrainingDetailScreen.kt
> +                        profile = (screenState as UiState.Success<ProfileWithTraining>).data.profile,
не красиво получается + неудобно, можно избавиться добавив локальную переменную -> val state = screenState

и потом использовать так if (state is UiState.Success && state.isChanged)

и так
```Kotlin
when (state) {
is UiState.Error -> {
                    ShowError(
                        message = stringResource(id = R.string.strava_server_unavailable)
                            .addLine(
                                state.exception.message.toString()
                            ),
                        onTryAgainClick = {
                            viewModel.fetchTraining(id = trainingId, isChanged = false)
                        }
                    )
                }

```

2023-06-16 20:42 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/training/detail/TrainingDetailScreen.kt
> +                        profile = (screenState as UiState.Success<ProfileWithTraining>).data.profile,
поправь везде где каст используешь

2023-06-16 20:42 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/main/MainScreenViewModel.kt
> +            when (val logoutDataResponse = logoutUseCase.logout()) {
окей

2023-06-16 20:42 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/presentation/main/MainScreenViewModel.kt
> +                    screenEventChannel.trySend(MainScreenEvent.NavigateToLogout(args = args))
окей

2023-06-16 20:42 UTC, TimurChikishev commented on app/src/main/java/ru/internetcloud/strava/data/firstlaunch/FirstLaunchSharedPreferencesStorage.kt
> +    fun isFirstLaunch(): Boolean = firstLaunchSharedPrefs.getBoolean(KEY_FIRST_LAUNCH, true)
Room и Retrofit сам поток переключает если методы suspend поэтому там пробемы такой нет

2023-06-22 06:13 UTC, harisov-mobile commented
Сделаны исправления в ДЗ № 7.

2023-06-22 06:14 UTC, merged